test_that("eras do vinculo: cbo94 2000-2003, cnae 2.0 de 2006", {
  expect_error(rais_era(1999, "vinculo"), "contrato")
  expect_identical(rais_era(2000, "vinculo"), "cnae95-cbo94")
  expect_identical(rais_era(2002, "vinculo"), "cnae95-cbo94")
  expect_identical(rais_era(2003, "vinculo"), "cnae95-cbo94")
  expect_identical(rais_era(2004, "vinculo"), "cnae95-cbo02")
  expect_identical(rais_era(2005, "vinculo"), "cnae95-cbo02")
  expect_identical(rais_era(2006, "vinculo"), "cnae20-cbo02")
  expect_identical(rais_era(2023, "vinculo"), "cnae20-cbo02")
  expect_identical(rais_era(2024, "vinculo"), "cnae20-cbo02")
  expect_identical(rais_era(2025, "vinculo"), "cnae20-cbo02")
})

test_that("eras do estabelecimento: tres trocas de padrao", {
  expect_identical(rais_era(2000, "estabelecimento"), "cnae95-clas-tamestab")
  expect_identical(rais_era(2001, "estabelecimento"), "cnae95-clas-tamestab")
  expect_identical(rais_era(2002, "estabelecimento"), "cnae95")
  expect_identical(rais_era(2005, "estabelecimento"), "cnae95")
  expect_identical(rais_era(2006, "estabelecimento"), "cnae20")
  expect_identical(rais_era(2023, "estabelecimento"), "cnae20")
  expect_identical(rais_era(2024, "estabelecimento"), "cnae20-dv")
})

test_that("rais_coluna resolve colunas por conceito/ano", {
  expect_identical(rais_coluna(2001, "vinculo", "cnae_2_0"), NA_character_)
  expect_identical(rais_coluna(2001, "vinculo", "cnae_95"), "cnae_95_classe")
  expect_identical(rais_coluna(2001, "vinculo", "cbo_94"), "cbo_94_ocupacao")
  expect_identical(rais_coluna(2004, "vinculo", "cnae_2_0"), NA_character_)
  expect_identical(rais_coluna(2004, "vinculo", "cnae_95"), "cnae_95_classe")
  expect_identical(rais_coluna(2004, "vinculo", "cbo_2002"), "cbo_ocupacao_2002")
  expect_identical(rais_coluna(2004, "vinculo", "cbo_94"), NA_character_)
  expect_identical(rais_coluna(2006, "vinculo", "cnae_2_0"), "cnae_2_0_classe")
  expect_identical(rais_coluna(2000, "estabelecimento", "porte"), "tamestab")
  expect_identical(rais_coluna(2000, "estabelecimento", "cnae_95"), "clas_cnae_95")
  expect_identical(rais_coluna(2002, "estabelecimento", "porte"), "tamanho_estabelecimento")
  expect_identical(rais_coluna(2002, "estabelecimento", "cnae_2_0"), NA_character_)
  expect_identical(rais_coluna(2006, "estabelecimento", "cnae_2_0"), "cnae_2_0_classe")
})

test_that("divisores seguem a granularidade da era", {
  expect_identical(rais_divisor(2013, "vinculo", "divisao"), 1000L)
  expect_identical(rais_divisor(2013, "vinculo", "grupo"), 100L)
  expect_identical(rais_divisor(2013, "vinculo", "classe"), 10L)
  # vinculo 2024+ continua 5d (sem DV)
  expect_identical(rais_divisor(2024, "vinculo", "grupo"), 100L)
  expect_identical(rais_divisor(2025, "vinculo", "classe"), 10L)
  # estabelecimento 2024+ tem DV (7d)
  expect_identical(rais_divisor(2024, "estabelecimento", "divisao"), 100000L)
  expect_identical(rais_divisor(2024, "estabelecimento", "grupo"), 10000L)
  # cnae_95 permanece 5 digitos em todas as eras
  expect_identical(rais_divisor(2024, "estabelecimento", "grupo", "cnae_95"), 100L)
  expect_error(rais_divisor(2001, "vinculo", "grupo", "cnae_2_0"), "ausente")
  expect_error(rais_divisor(2005, "vinculo", "grupo", "cnae_2_0"), "ausente")
})
